### ISSUE TITLE
Minor issues with the README

### ISSUE THREAD

**Issue by divs1210** [stopachka/godel-numbers#1]
Let me start by thanking you for the article.
It is really well written, and was a fun and enlightening read!

Just have 2 suggestions for the README:
- It will be great if it would link to the article
- there's a bug in the example: `(pm-lisp->godel-num '(next 0)` is missing a `)`

**Comment by stopachka** [comment]
Cheers @divs1210 -- if you like feel free to pop in a PR update to the README  -- (can do so, but thought it would be cool for this repo to have had a contributor! :))

**Comment by divs1210** [comment]
Raised a PR! 🙂

**Comment by stopachka** [comment]
_sends high five_
